# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://4pondsfarm.ca'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: 4 Ponds Farm
# Description of the Site
description: A grass fed beef farm
# URL of Image of the Site
site-image:
# Keywords of the Site
site-keywords: 4PondsFarm, 4, Ponds, Farm, Grass, Grass-fed, Beef, Food, Organic, Natural, OrganicBeef, NaturalBeef, ScottishHighlands, Scottish, Highlands, Cows, Cattle

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/highland-banner.png

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: probst.highland@gmail.com
facebook_username: 4PondsFarm
twitter_username:
instagram_username:
linkedin_username:
github_username:
youtube_channel_id:
reddit_username:
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics:

# Disqus
disqus-shortname:

# Name of the Author
author-name: 4PondsFarm
# URL for the Image of the Author
author-image: /assets/images/highland-cow-calf.jpg
# 60 Words About the Author
author-about: >
  4PondsFarm is where the Probst family maintains a purebred herd of Scottish Highland cattle.
  They are grass fed and naturally raised without hormones, antibiotics, or pesticides. This breed
  is very well adapted and has been kept true to form since recorded history, never loosing
  their ability to thrive on grass alone. Furthermore, studies show that Highland beef is lower in
  fat and cholesterol and higher in protein and iron than other beef. The result is richly favoured
  and well-marbled beef.

# Additional paragraph
author-about2: >
  Our beef is dry aged and is cut and wrapped to your specifications by the half. Our animals are
  generally 18 months old or younger and the sides weigh from 175 to 275 lbs.

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url:

# Pricing paragraph
pricing: >
  We currently have beef available to purchase by the side or whole. The price is $5.50 per pound
  (hanging weight). This includes custom cutting, wrapping, and freezing of your order. Reserve your
  side now for butchering in October. Available while supplies last.

# URL for pricing image
pricing-image: /assets/images/ground-beef-packages.jpg

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
